#!/bin/bash

# INFO — Synology DSM 7 Package Metadata
# Generated by synocat (https://github.com/synocatjs/synocat)
# Field docs: synocat info <fieldname>

source /pkgscripts/include/pkg_util.sh

# === Required fields ===
package="basic"
version="1.0.0-0001"
os_min_ver="7.0-40000"
maintainer="sim"
description="test synocat"
arch="noarch"


# === Package behaviour ===
displayname="basic"


# === Generate INFO function ===
pkg_dump_info
