#!/bin/bash
# Copyright (C) 2000-2020 Synology Inc. All rights reserved.

### Use PKG_DIR as working directory.
PKG_DIR=/tmp/_test_spk
rm -rf $PKG_DIR
mkdir -p $PKG_DIR

### get spk packing functions
source /pkgscripts/include/pkg_util.sh

create_package_tgz() {
	local package_tgz_dir=/tmp/_package_tgz
	local binary_dir=$package_tgz_dir/usr/local/bin

	### clear destination directory
	rm -rf $package_tgz_dir && mkdir -p $package_tgz_dir

	### install demo binary
	mkdir -p $binary_dir
	cp -av ../demo $binary_dir
	
	### 如果需要使用 make install，可以调用（可选）
	# 设置 PKG_NAME 环境变量
	# export PKG_NAME="mini-app"
	# make -C .. install DESTDIR="$package_tgz_dir"
	
	### create package.tgz
	pkg_make_package $package_tgz_dir "${PKG_DIR}"
}

create_spk(){
	# 复制 scripts（如果存在）
	if [ -d ../scripts ]; then
		cp -av ../scripts $PKG_DIR/scripts
	fi
	
	# 复制图标
	if ls ../PACKAGE_ICON*.PNG 1> /dev/null 2>&1; then
		cp -av ../PACKAGE_ICON*.PNG $PKG_DIR
	fi
	
	# 复制 conf
	if [ -d ../conf ]; then
		cp -av ../conf $PKG_DIR
	fi
	
	# 复制 LICENSE（如果存在）
	if [ -f ../LICENSE ]; then
		cp -av ../LICENSE $PKG_DIR
	fi

	# 使用现有的 INFO 文件
	if [ -f ../INFO ]; then
		cp ../INFO $PKG_DIR/INFO
	else
		echo "Error: INFO file not found!"
		exit 1
	fi

	### Create the final spk.
	mkdir -p /image/packages
	pkg_make_spk ${PKG_DIR} "/image/packages" $(pkg_get_spk_family_name)
}

main() {
	create_package_tgz
	create_spk
}

main "$@"