[
  {
    "step_title": "欢迎安装 Markdown Editor",
    "items": [
      {
        "type": "textfield",
        "desc": "安装路径 (默认使用系统卷)",
        "subitems": [
          {
            "key": "pkgwizard_install_volume",
            "desc": "安装到卷",
            "defaultValue": "/volume1",
            "validator": {
              "allowBlank": false
            }
          }
        ]
      }
    ]
  },
  {
    "step_title": "确认安装",
    "items": [
      {
        "type": "textfield",
        "desc": "Markdown Editor 将安装到您的 Synology NAS。安装完成后，可在 DSM 桌面找到应用图标。",
        "subitems": []
      }
    ]
  }
]
