#!/bin/bash
# Copyright (C) 2000-2020 Synology Inc. All rights reserved.

### Use PKG_DIR as working directory.
PKG_DIR=/tmp/_test_spk
rm -rf $PKG_DIR
mkdir -p $PKG_DIR

### get spk packing functions
source /pkgscripts/include/pkg_util.sh

create_package_tgz() {
	local package_tgz_dir=/tmp/_package_tgz
	local binary_dir=$package_tgz_dir/usr/local/bin

	### clear destination directory
	rm -rf $package_tgz_dir && mkdir -p $package_tgz_dir

	### install demo binary
	mkdir -p $binary_dir
	
	if [ -f /source/mini-app/demo ]; then
		cp -av /source/mini-app/demo $binary_dir
	else
		echo "Error: demo binary not found!"
		exit 1
	fi

	### create package.tgz
	pkg_make_package $package_tgz_dir "${PKG_DIR}"
}

create_spk(){
	# 生成 INFO 文件
	if [ -f /source/mini-app/INFO.sh ]; then
		cd /source/mini-app
		./INFO.sh > INFO
		cd /source/mini-app/SynoBuildConf
	fi
	
	# 复制文件
	[ -d /source/mini-app/scripts ] && cp -av /source/mini-app/scripts $PKG_DIR/scripts
	ls /source/mini-app/PACKAGE_ICON*.PNG 2>/dev/null && cp -av /source/mini-app/PACKAGE_ICON*.PNG $PKG_DIR
	[ -d /source/mini-app/conf ] && cp -av /source/mini-app/conf $PKG_DIR
	
	# 复制 INFO
	[ -f /source/mini-app/INFO ] && cp /source/mini-app/INFO $PKG_DIR/INFO

	### Create the final spk
	mkdir -p /image/packages
	pkg_make_spk ${PKG_DIR} "/image/packages" $(pkg_get_spk_family_name)
}

main() {
	create_package_tgz
	create_spk
}

main "$@"